### PR TITLE
use the proper decimal point in ObjectDatum

### PR DESCRIPTION
**Pull request by etienneroudeix**
based on locale get the proper decimal point and use it in date format parsing

### CODE REVIEW

**Comment by danielmewes** [comment]
Thanks for the PR @etienneroudeix . Are you actually seeing failures when storing (or reading) date/time objects from RethinkDB without this change?

**Comment by etienneroudeix** [comment]
Hello @danielmewes Yes indeed, it's failing when locale is FR. It cannot manage to parse date using "." ("," expected) when reading data with microseconds.

**Comment by danielmewes** [comment]
Sorry for the delay. This looks good, merging.

**Comment by etienneroudeix** [comment]
Hello @danielmewes, when are you planning to make a new release ?

**Comment by ed-piisang** [comment]
Seeing as @danielmewes is not very active, same question to
@AtnNn 
@coffeemug
@mglukhovsky
@mlucy 
@neumino
@timmaxw
@VeXocide
@Tryneus

Would be nice to see a bugfix release at least.

**Comment by ghost** [comment]
FWIW: Published https://packagist.org/packages/ekspress-digital/php-rql version 2.3.1 : https://github.com/ekspress-digital/php-rql/releases/tag/2.3.1

**Comment by ghost** [comment]
@etienneroudeix you might be interested?

**Pull request merged**
